### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by ZHANGHSING** [SummerGGift/micropython_for_w601#2]
keil编译：.\build\keil\Obj\rtthread-w60x.axf: error: L6002U: Could not open file libraries\WM_Libraries\Lib\Wlan\libwlan_mdk.lib: No such file or directory

scons编译：makeimg err! No makeimg file found: D:/micropython_for_w601-master/libraries/WM_Libraries/Tools/makeimg.exe

希望能补全文件。。。

**Comment by SummerGift** [comment]
因为 git 忽略的原因漏提交了一些文件，现在文件已经补全了，谢谢提醒。
